"""Phase 13: download VisDrone2019-DET (via Ultralytics' built-in
downloader/converter) and remap its 10 classes down to our 5 vehicle
classes for fine-tuning.

Note on raw vs. processed: Ultralytics' own VisDrone.yaml download
script already converts the original CSV-style annotations straight to
YOLO .txt format and deletes the intermediate files - there's no
meaningful "raw" VisDrone format left to preserve separately from
"processed". So unlike the sample traffic clips, this dataset is
downloaded and class-remapped in place under data/raw/VisDrone rather
than kept as a separate data/processed/ copy - duplicating ~2GB of
images just to satisfy the raw/processed split would cost real disk
for no benefit.

VisDrone's official train/val/test-dev split is already by distinct
video sequence, not by individual frame, so there's no data leakage
risk to guard against here (see project notes on avoiding leakage).

Class mapping (VisDrone id -> our id, None = dropped):
  0 pedestrian      -> None (not a vehicle)
  1 people          -> None (not a vehicle)
  2 bicycle         -> 0 bicycle
  3 car             -> 1 car
  4 van             -> 1 car       (merged - visually near-identical to car)
  5 truck           -> 4 truck
  6 tricycle        -> None (doesn't map cleanly to any of our 5 classes)
  7 awning-tricycle -> None (ditto)
  8 bus             -> 3 bus
  9 motor           -> 2 motorcycle
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.utils.config import resolve_path

VISDRONE_TO_OURS = {
    2: 0,  # bicycle -> bicycle
    3: 1,  # car -> car
    4: 1,  # van -> car
    5: 4,  # truck -> truck
    8: 3,  # bus -> bus
    9: 2,  # motor -> motorcycle
}
OUR_CLASS_NAMES = {0: "bicycle", 1: "car", 2: "motorcycle", 3: "bus", 4: "truck"}

SPLITS = ["train", "val", "test"]


def download_and_convert():
    from ultralytics.data.utils import check_det_dataset

    print("Downloading + converting VisDrone2019-DET (this triggers Ultralytics' "
          "built-in downloader if not already present)...")
    data_info = check_det_dataset("VisDrone.yaml")
    print(f"Dataset ready at: {data_info['path']}")
    return Path(data_info["path"])


def remap_labels(dataset_root: Path):
    # Our class ids (0-4) partially overlap VisDrone's original ids (2-9), so
    # remapping already-remapped labels a second time would silently corrupt
    # them (e.g. id 2 means "motorcycle" in our scheme but "bicycle" in
    # VisDrone's) - guard against rerunning this by mistake.
    sentinel = dataset_root / "labels" / ".remapped_to_5_vehicle_classes"
    if sentinel.exists():
        print(f"  labels already remapped (found {sentinel}), skipping to avoid double-remapping")
        return

    total_before = {name: 0 for name in OUR_CLASS_NAMES.values()}
    total_after = {name: 0 for name in OUR_CLASS_NAMES.values()}

    for split in SPLITS:
        labels_dir = dataset_root / "labels" / split
        if not labels_dir.exists():
            print(f"  {split}: no labels dir found, skipping")
            continue

        label_files = list(labels_dir.glob("*.txt"))
        for label_file in label_files:
            lines = label_file.read_text(encoding="utf-8").strip().splitlines()
            kept_lines = []
            for line in lines:
                parts = line.split()
                if not parts:
                    continue
                visdrone_cls = int(parts[0])
                if visdrone_cls in VISDRONE_TO_OURS:
                    total_before[OUR_CLASS_NAMES[VISDRONE_TO_OURS[visdrone_cls]]] += 1
                    new_cls = VISDRONE_TO_OURS[visdrone_cls]
                    kept_lines.append(" ".join([str(new_cls)] + parts[1:]))
            label_file.write_text("\n".join(kept_lines) + ("\n" if kept_lines else ""), encoding="utf-8")
            for line in kept_lines:
                total_after[OUR_CLASS_NAMES[int(line.split()[0])]] += 1

        print(f"  {split}: remapped {len(label_files)} label files")

    print("\nBox counts kept after remap (per class, across all splits):")
    for name, count in total_after.items():
        print(f"  {name}: {count}")

    sentinel.write_text("Labels in this dataset have already been remapped to our 5 vehicle "
                         "classes by prepare_visdrone.py - do not remap again.\n", encoding="utf-8")


def write_dataset_yaml(dataset_root: Path):
    yaml_path = resolve_path("training/dataset.yaml")
    lines = [
        "# Auto-generated by training/prepare_visdrone.py - rerun that script rather than",
        "# hand-editing this file. `path` is machine-specific (absolute).",
        f"path: {dataset_root.as_posix()}",
        "train: images/train",
        "val: images/val",
        "test: images/test",
        "",
        "names:",
    ]
    for cls_id, name in OUR_CLASS_NAMES.items():
        lines.append(f"  {cls_id}: {name}")
    yaml_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nWrote training data config to: {yaml_path}")


def main():
    dataset_root = download_and_convert()
    print("\nRemapping VisDrone's 10 classes down to our 5 vehicle classes...")
    remap_labels(dataset_root)
    write_dataset_yaml(dataset_root)


if __name__ == "__main__":
    main()
